### ISSUE TITLE
quanti_save_phenotype does not report the correct patch

### ISSUE THREAD

**Issue by jgx65** [jgx65/quantinemo#26]
the patch reported with `quanti_save_phenotype` set to 1 is always patch 1.

**Comment by frederic-michaud** [comment]
Hi Jérôme,

Sorry. I don't get what the problem is exactly. Only individual from patch 1 are saved? Can you provide an input file as an example?
Thanks!

Frédéric

**Comment by jgx65** [comment]
The first column of output files `pheno_g200_r*.phe` is made of 1s only instead of the corresponding patch number.  

```
# Simulations
generations 200
replicates 10
folder "Island"
random_per_replicate 1

# Metapopulation
patch_number 12
patch_capacity 50
dispersal_rate 0.02


# Quantitative trait
quanti_nb_trait 1
quanti_loci 10
quanti_all  2
quanti_mutation_model  2
quanti_mutation_rate 1e-5
quanti_allelic_var 0.005
quanti_environmental_model 0
quanti_heritability 0
quanti_environmental_proportion 1
quanti_va_model 1

quanti_save_phenotype 1
quanti_phenot_logtime 200
quanti_phenot_filename "pheno"

```

**Comment by frederic-michaud** [comment]
Hello Jérôme,

Do you have a way to compile the code to see if the last commit 790ef30 solved your problem?

Cheers,
Frédéric

**Comment by jgx65** [comment]
Hello Frederic, this one is solved, many thanks!

Jérôme Goudet
Dept. Ecology & Evolution
Biophore, UNIL-Sorge
CH-1015 Lausanne
http://www.unil.ch/dee/goudet-group
mail:jerome.goudet@unil.ch
Tel:+41 (0)21 692 4242
