### ISSUE TITLE
Overwrite of file with sequencial parameter

### ISSUE THREAD

**Issue by frederic-michaud** [jgx65/quantinemo#30]
In the case of sequencial parameter, when the folder is specified, the output statistics get overwritten because all file has the same name. 

```
generations 200
patch_capacity 50 100 150
folder = simulate
stat {adlt.nbInd}
```

This does not happen if the simulation is longer than 1s, and that the argument _folder_ is not specified because in this case, the different result are written in different folder using a timestamp.

**Comment by jgx65** [comment]
@frederic-michaud : tried it with sequential parameters (the example I give in #29 ), it works partially only: one `_stats.txt` file is created for each of the sequential parameter, but only the last replicate is saved when using `stat_save 1`. It works perfectly with `stat_save 0`

**Comment by frederic-michaud** [comment]
Hello @jgx65 ,
Yes, I agree, this is why #24 is still open. I don't have a solution for that yet. The question is if we can close this ticket, and just continue working on #24.

**Comment by jgx65** [comment]
yes, ticket can be closed and branch merged with master I believe, unless you feel a more thorough check is necessary?

**Comment by frederic-michaud** [comment]
Test done. Closing this issue.
