### ISSUE TITLE
patch_sample_size keyword

### ISSUE THREAD

**Issue by jgx65** [jgx65/quantinemo#33]
Using `patch_sample_size` affects the results of the simulation and should not be used for the time being

**Comment by frederic-michaud** [comment]
Hi @jgx65 , would it be possible to have a simple example showing the problem? 
Thanks,
Frédéric

**Comment by jgx65** [comment]
Hi @frederic-michaud , Thanks for your speedy answer!  I cannot replicate the issue, I was getting different FST values in an island model depending on whether I was subsampling within `quantiNemo` or outside, but it might have been because I had very strong selection.  I'm closing the issue and will re-open it if it occurs again.
